// +build !ignore_autogenerated

/*
Piraeus Operator
Copyright 2019 LINBIT USA, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinstorCSIDriver) DeepCopyInto(out *LinstorCSIDriver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinstorCSIDriver.
func (in *LinstorCSIDriver) DeepCopy() *LinstorCSIDriver {
	if in == nil {
		return nil
	}
	out := new(LinstorCSIDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinstorCSIDriver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinstorCSIDriverList) DeepCopyInto(out *LinstorCSIDriverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinstorCSIDriver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinstorCSIDriverList.
func (in *LinstorCSIDriverList) DeepCopy() *LinstorCSIDriverList {
	if in == nil {
		return nil
	}
	out := new(LinstorCSIDriverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinstorCSIDriverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinstorCSIDriverSpec) DeepCopyInto(out *LinstorCSIDriverSpec) {
	*out = *in
	if in.ControllerReplicas != nil {
		in, out := &in.ControllerReplicas, &out.ControllerReplicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeTolerations != nil {
		in, out := &in.NodeTolerations, &out.NodeTolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ControllerAffinity != nil {
		in, out := &in.ControllerAffinity, &out.ControllerAffinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.ControllerTolerations != nil {
		in, out := &in.ControllerTolerations, &out.ControllerTolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.LinstorClientConfig = in.LinstorClientConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinstorCSIDriverSpec.
func (in *LinstorCSIDriverSpec) DeepCopy() *LinstorCSIDriverSpec {
	if in == nil {
		return nil
	}
	out := new(LinstorCSIDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinstorCSIDriverStatus) DeepCopyInto(out *LinstorCSIDriverStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinstorCSIDriverStatus.
func (in *LinstorCSIDriverStatus) DeepCopy() *LinstorCSIDriverStatus {
	if in == nil {
		return nil
	}
	out := new(LinstorCSIDriverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinstorClientConfig) DeepCopyInto(out *LinstorClientConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinstorClientConfig.
func (in *LinstorClientConfig) DeepCopy() *LinstorClientConfig {
	if in == nil {
		return nil
	}
	out := new(LinstorClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SatelliteStatus) DeepCopyInto(out *SatelliteStatus) {
	*out = *in
	out.NodeStatus = in.NodeStatus
	if in.StoragePoolStatuses != nil {
		in, out := &in.StoragePoolStatuses, &out.StoragePoolStatuses
		*out = make([]*StoragePoolStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StoragePoolStatus)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SatelliteStatus.
func (in *SatelliteStatus) DeepCopy() *SatelliteStatus {
	if in == nil {
		return nil
	}
	out := new(SatelliteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolLVM) DeepCopyInto(out *StoragePoolLVM) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolLVM.
func (in *StoragePoolLVM) DeepCopy() *StoragePoolLVM {
	if in == nil {
		return nil
	}
	out := new(StoragePoolLVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolLVMThin) DeepCopyInto(out *StoragePoolLVMThin) {
	*out = *in
	out.StoragePoolLVM = in.StoragePoolLVM
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolLVMThin.
func (in *StoragePoolLVMThin) DeepCopy() *StoragePoolLVMThin {
	if in == nil {
		return nil
	}
	out := new(StoragePoolLVMThin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolStatus) DeepCopyInto(out *StoragePoolStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolStatus.
func (in *StoragePoolStatus) DeepCopy() *StoragePoolStatus {
	if in == nil {
		return nil
	}
	out := new(StoragePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePools) DeepCopyInto(out *StoragePools) {
	*out = *in
	if in.LVMPools != nil {
		in, out := &in.LVMPools, &out.LVMPools
		*out = make([]*StoragePoolLVM, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StoragePoolLVM)
				**out = **in
			}
		}
	}
	if in.LVMThinPools != nil {
		in, out := &in.LVMThinPools, &out.LVMThinPools
		*out = make([]*StoragePoolLVMThin, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StoragePoolLVMThin)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePools.
func (in *StoragePools) DeepCopy() *StoragePools {
	if in == nil {
		return nil
	}
	out := new(StoragePools)
	in.DeepCopyInto(out)
	return out
}
